alias: Cookie Last Fed Time
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.cookie_fed
    from: "off"
    to: "on"
condition: []
action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.cookie_last_fed
    data_template:
      datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
mode: single
